### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'enable_eager_execution'

### ISSUE THREAD

**Issue by farzadmohseni-ir** [ElmiiiRaa/machine-translation#1]
**_When running with Python 3.8.3 , even though all the libraries are installed, I get the following error :_**

AttributeError: module 'tensorflow' has no attribute 'enable_eager_execution'

![1](https://user-images.githubusercontent.com/57835828/110290333-ec227000-7fff-11eb-8415-1c437f0f4b14.jpg)

Please help fix the bug and run the project .

**Comment by farzadmohseni-ir** [comment]
**The following error can be fixed according to the evidence in stackoverflow.**

https://stackoverflow.com/questions/57218559/unable-to-enable-tensorflows-eager-execution

![3](https://user-images.githubusercontent.com/57835828/110448515-82c16080-80d6-11eb-8036-2c220a377238.jpg)

![1](https://user-images.githubusercontent.com/57835828/110448540-86ed7e00-80d6-11eb-83ce-fc25b57ffa0e.jpg)

![2](https://user-images.githubusercontent.com/57835828/110448569-8b199b80-80d6-11eb-8fd7-ae215cb68554.jpg)


**Now, by executing the code, we will get a directory error that you did not publish such a file in the post . **_" fra.txt "_**
if possible Update project files .**

**Comment by ElmiraGhorbani** [comment]
> **The following error can be fixed according to the evidence in stackoverflow.**
> 
> https://stackoverflow.com/questions/57218559/unable-to-enable-tensorflows-eager-execution
> 
> ![3](https://user-images.githubusercontent.com/57835828/110448515-82c16080-80d6-11eb-8036-2c220a377238.jpg)
> 
> ![1](https://user-images.githubusercontent.com/57835828/110448540-86ed7e00-80d6-11eb-83ce-fc25b57ffa0e.jpg)
> 
> ![2](https://user-images.githubusercontent.com/57835828/110448569-8b199b80-80d6-11eb-8fd7-ae215cb68554.jpg)
> 
> **Now, by executing the code, we will get a directory error that you did not publish such a file in the post . **_" fra.txt "_** if possible Update project files .**

Yes, the problem you mentioned depends on Tensorflow version.
for run translation.py you need train network.
check train_model.ipynb.
use clean_data/clean_cleaned.txt as dataset.

**Comment by farzadmohseni-ir** [comment]
**Due to new versions of libraries used in the project , bugs have been created .
Two of them can be fixed according to the documentation available in stackoverflow :**

> https://stackoverflow.com/questions/55318273/tensorflow-api-v2-train-has-no-attribute-adamoptimizer
> https://stackoverflow.com/questions/57218559/unable-to-enable-tensorflows-eager-execution

> 1 )  tf.train.AdamOptimizer ()  ==>  tf.optimizers.Adam ()
> 2 )  tf.enable_eager_execution ()  ==>  tf.compat.v1.enable_eager_execution ()

**Now considering the other bugs that have been created , Please help me fix them so I can run the project .**

> 1 - http://prntscr.com/10hp4fs
> 2- http://prntscr.com/10hp5li
> 3 - http://prntscr.com/10hp79i
> 4 - http://prntscr.com/10hp8rt
> 5 - http://prntscr.com/10hp9pz
> 6 - http://prntscr.com/10hpfog
> 7- http://prntscr.com/10hph78
> 8 - http://prntscr.com/10hpi9i
> 9 - http://prntscr.com/10hpiwt
> 10 - http://prntscr.com/10hpjo8
> 11 - http://prntscr.com/10hpkkb
> 12 - http://prntscr.com/10hplbx
> 13 - http://prntscr.com/10hpmcc
> 14 - http://prntscr.com/10hpn7w
> 15 - http://prntscr.com/10hpo72
> 16 - http://prntscr.com/10hpp9j
> 17 - http://prntscr.com/10hpq77
> 18 - http://prntscr.com/10hpqwg

**Run ==>** https://www.screencast.com/t/AaFPm0pHTuH

**_Thanks_**
